export default class EventList {
    static RELOAD_SCREEN_DATA = 'RELOAD_SCREEN_DATA';

    static ON_PRESS_BUY_SELL_MARKET_DETAIL_SCREEN = 'ON_PRESS_BUY_SELL_MARKET_DETAIL_SCREEN';

    static SHOW_TRADE_SCREEN_DROPDOWN = 'SHOW_TRADE_SCREEN_DROPDOWN';

    static RELOAD_SCREEN_DATA_FAVOURITE = 'RELOAD_SCREEN_DATA_FAVOURITE';

    static RELOAD_SCREEN_DATA_LANGUAGE = 'RELOAD_SCREEN_DATA_LANGUAGE';

    static RELOAD_AML_TOTAL = 'RELOAD_AML_TOTAL';

    static SHOW_TOTAL_AML_REMAIN = 'SHOW_TOTAL_AML_REMAIN';

    static RELOAD_AML_PRICE = 'RELOAD_AML_PRICE';

    static RELOAD_ORDER_FORM_SALE_POINT = 'RELOAD_ORDER_FORM_SALE_POINT';

    static RELOAD_BALANCE_WITHDRAW_SUCCESS = 'RELOAD_BALANCE_WITHDRAW_SUCCESS';

    static RESET_TIME_FILTER = 'RESET_TIME_FILTER';

    static SEARCH_TRANSACTIONS = 'SEARCH_TRANSACTIONS';

    static RESET_DATA_FILTER = 'RESET_DATA_FILTER';

    static CLOSE_DRAWER_ORDER_HISTORY = 'CLOSE_DRAWER_ORDER_HISTORY';
}
